### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by dansup** [bostonmeshnet/website#3]
I was thinking it would be best to add the email that is collected to a mailing list, to organize discussion. We have two simple options:
- Use [Project Meshnet Mailing Lists](https://lists.projectmesh.net/cgi-bin/mailman/listinfo/boston)
  or
- Use [Mailgun](https://documentation.mailgun.com/api-mailinglists.html)

@bostonmeshnet/owners Feedback appreciated!

**Comment by wfleurant** [comment]
i'd say the pm mailing list since its TLS and already set up.. Might make an anchor with target="_blank"
